### PR TITLE
Add border to label

### PR DESCRIPTION
**Pull request by fti-pfarne**
### Description

- #411 
- This PR is enhancement in LineUI Label .
- The problem is the background of the map is white and the label of the polygon area they draw is also white and label color is also white so label is not visible in white background.

- For that I have added border from label text. 

### Considerations on Implementation

- Added CSS for border.

### Screenshot

- Initially it look like this

Screenshot from 2023-06-05 18-14-35

Screenshot from 2023-06-05 18-14-15

- I have added CSS so it looks like this as below

Screenshot from 2023-06-05 18-11-31

### CODE REVIEW

**Review by fti-skumar — APPROVED** [review]
LGTM!

**Review by fti-bcarpenter — CHANGES_REQUESTED** [review]
This PR implementation is making this text-shadow compulsory on Line UI but this feature should be controlled with props.

**Comment by fti-skumar** [comment]
> This PR implementation is making this text-shadow compulsory on Line UI but this feature should be controlled with props.

**Fixed.**

**I have also added toggle to change prop for text shadow.**

image

image

@fti-bcarpenter sir, please review it again.

**Review by fti-bcarpenter — APPROVED** [review]
LGTM

**Review by atomworks — APPROVED** [review]

**Pull request merged**
