### PR TITLE
Fix bug in preserve keep-open/auto-hide state in menu

### PR DESCRIPTION
**Pull request by fti-pvishwakarma**
### Description

 This PR for fixing Bug in previous PR  [preserve keep-open/auto-hide state in menu](https://github.com/future-standard/scorer-ui-kit/pull/296) 

Bug found if pass props canAlwaysPin = true then if screen  resolution width more then 1400px and refresh page then it show Auto-Hide and auto close menu, it's not expected behavior.

### Reviewing/Testing steps
Please follow the previous PR instructions. [LINK](https://github.com/future-standard/scorer-ui-kit/pull/296)

### CODE REVIEW

**Comment by isacoder** [comment]
@fti-pvishwakarma  your update was not fixing the "auto-close" issue in big screens.
I made a refactor of this part on your PR, please review and let me know if the behaivour is correct now.

@fti-bcarpenter please help reviewing my changes to make a faster merge of this PR

**Comment by fti-pvishwakarma** [comment]
> @fti-pvishwakarma your update was not fixing the "auto-close" issue in big screens. I made a refactor of this part on your PR, please review and let me know if the behaivour is correct now.
> 
> @fti-bcarpenter please help reviewing my changes to make a faster merge of this PR

@isacoder  Thanks for your patience, it's work as expected.

**Comment by fti-pvishwakarma** [comment]
> > @fti-pvishwakarma your update was not fixing the "auto-close" issue in big screens. I made a refactor of this part on your PR, please review and let me know if the behaivour is correct now.
> > @fti-bcarpenter please help reviewing my changes to make a faster merge of this PR
> 
> @isacoder Thanks for your patience, it's working as expected.

**Comment by fti-pvishwakarma** [comment]
@isacoder  I request you to merge this PR so that I can update the new version.

**Comment by isacoder** [comment]
Hello @fti-pvishwakarma, not sure I understand what you mean, you have closed this PR 🤔 

Are you sending a new PR?

**Comment by fti-pvishwakarma** [comment]
> Hello @fti-pvishwakarma, not sure I understand what you mean, you have closed this PR 🤔
> 
> Are you sending a new PR?

@isacoder  Sorry for this, PR closed by mistake  I have raised a new PR, Please review it.
[Follow this link https://github.com/future-standard/scorer-ui-kit/pull/315](https://github.com/future-standard/scorer-ui-kit/pull/315)

**Pull request closed without merging**
